// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"
)

type Video struct {
	ID          string
	Title       string
	Url         string
	PublishedAt time.Time
	PlaylistID  string
}
