// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"time"
)

const getKnownVideoIDs = `-- name: GetKnownVideoIDs :many
SELECT id FROM videos WHERE playlist_id = ?
`

func (q *Queries) GetKnownVideoIDs(ctx context.Context, playlistID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getKnownVideoIDs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveVideo = `-- name: SaveVideo :exec
INSERT INTO videos (id, title, url, published_at, playlist_id) VALUES (?, ?, ?, ?, ?)
`

type SaveVideoParams struct {
	ID          string
	Title       string
	Url         string
	PublishedAt time.Time
	PlaylistID  string
}

func (q *Queries) SaveVideo(ctx context.Context, arg SaveVideoParams) error {
	_, err := q.db.ExecContext(ctx, saveVideo,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.PublishedAt,
		arg.PlaylistID,
	)
	return err
}
